### ISSUE TITLE
missing file options-ssl.conf?

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#155]
when i run the tests, a lot of them fail due to this:

ERROR: test_add_name_vhost (letsencrypt.client.tests.apache_configurator_test.TwoVhost80Test)

Traceback (most recent call last):
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/tests/apache_configurator_test.py", line 29, in setUp
    self.ssl_options = config_util.setup_apache_ssl_options(self.config_dir)
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/tests/config_util.py", line 34, in setup_apache_ssl_options
    temp_options, option_path)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/tw/w/lets-encrypt-preview/letsencrypt/client/options-ssl.conf'

**Comment by jdkasten** [comment]
My fault... it should only affect the tests and not the actual code.  
Relevant issue: #150.

I will fix the testing code shortly.

**Comment by jdkasten** [comment]
Thanks for noticing this @ThomasWaldmann .  I have been working on other projects the past week and thought I had made a quick fix for a small issue and forgot to update the testing code.  TravisCI is now giving out the expected results right now and it appears this issue is resolved.

I will be spending all of my time this next week on the code so there should be some faster development/testing turn around.

Best,
James

**Comment by ThomasWaldmann** [comment]
thanks for fixing it so quickly :)
