### ISSUE TITLE
fix travis CI (linter)

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#178]
it is a bit annoying that the Travis CI tests always fail - and it is not because failing (new) code, but because of the linter.

so I suggest to either remove the linter run for travis for now or to fix it.

**Comment by jdkasten** [comment]
Yeah... this has been on my TODO list for awhile.  I have a few ideas about the matter.

I believe that having pylint compliant testcases is not tenable.
1. test functions should have long names, pylint doesn't like it.
2. documentation requirements are a pain for the test classes.
3. I believe that you should be able to test "private" functions without having to disable protected-access on pylint.  It just encourages you to find another way to test it rather than writing the tests that you actually want to write.

So at the very least, I propose removing pylint from watching the tests package.

I am not that familiar with pylint/travis ci integration.  What I believe I would want right now is for lint to crash when there is a big error, but temporarily ignore minor things right now.  I think it is helpful to have pylint list all of the TODOs in all of the files, but I don't want pylint crashing because there are TODOs in the project.  (It will encourage people to silently keep things to themselves)

I haven't spent that much time with pylint.  I believe there is an option (-E i believe) that turns off all errors that aren't major, but I think it also completely hides all of the minor things.  Which I still like to look at and try to remove if possible.

Does anyone have more experience with these matters?

**Comment by kuba** [comment]
Fixed in #186.
