### ISSUE TITLE
"NullConfigurator" Implementation

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/lets-encrypt-preview#63]
This has been a highly requested feature.  We would like to allow all servers to receive a trusted certificate even if the project doesn't fully support their system with proper configuration.

This would involve creating a new "NullConfigurator" class (I am not tied to the name, you may call it what you like :) ).  This class would essentially only perform challenges for a given domain name and output the certificate, key, and chain file at the end. (in the current working directory)

In order to perform the challenges you will have use a crypto library or spin up a lightweight server to help you perform the challenges.  The challenges are at the bottom of the document here - https://github.com/letsencrypt/acme-spec/blob/master/draft-barnes-acme.txt

It would be the admins job to install the certificate, but this would enable all webserver to attain a certificate, no matter what system they are running.

(If you only want to contribute by supporting one of the challenges to begin with.. it would still be a major help.)

**Comment by ThomasWaldmann** [comment]
what's the current state of this? @schoen ?

**Comment by schoen** [comment]
Hi folks, I have just made an initial commit on the "standalone_authenticator" branch.  We tested this today and succeeded in getting cert issuance from the demo server (although please note that there is not yet any UI path to invoke this configurator -- we temporarily modified main.py to call into this instead of the Apache configurator).

This implementation creates a subprocess which then listens on CONFIG.PORT (default 443) and performs specified DVSNI challenges there.  My preference (which I'll write up in a longer document) is to use pure-Python implementations of a small number of TLS protocol handshake messages (instead of a complete TLS implementation), but for backwards compatibility with existing verifiers, which use ordinary TLS implementations, I have also written code to use PyOpenSSL (which will be a new dependency for this branch).  The reason for selecting PyOpenSSL is that it has support for SNI on the server side, which we need for a complete DVSNI implementation.

**Comment by schoen** [comment]
@jdkasten is working on the UI aspect, probably initially providing the user with a menu of available configurators, and we'll also look at the name under which the Let's Encrypt client was run (e.g. lets-encrypt-standalone, lets-encrypt-apache, lets-encrypt-nginx...) to decide which configurator to use.

**Comment by kuba** [comment]
re PyOpenSSL: #164

**Comment by schoen** [comment]
I submitted PR #232 to merge the standalone authenticator.

**Comment by schoen** [comment]
This is now implemented via the merge of #232. Soon we will also have a user interface available to invoke it. :-)
